"""
DP-aware Mahalanobis attack variants.

These are thin wrappers around the standard attack_mahalanobis / attack_mahalanobis_no_aux
that inject (ε, δ)-DP Gaussian noise into the synthetic copula's covariance matrix
before running the attack.

Purpose
-------
Simulates the scenario in which scDesign2/3's Gaussian copula is released with
DP noise injected at training time.  The attacker receives the noised copula and
can do no better against it than the original attack against the noiseless one.

This is used to generate the privacy-utility tradeoff curve (Experiment 1 in
the RECOMB revision).

Threat-model note
-----------------
The DP noise is applied to the *synthetic* copula only (not the auxiliary one).
In the white-box setting the synthetic copula IS the training copula; in the
black-box setting it would be estimated from synthetic data generated by the
DP-noised training copula.  For simplicity, these functions implement the
white-box version; a black-box DP runner requires re-generating synthetic data
from the noised copula (see experiments/dp/README.md for the full pipeline).

Usage
-----
Call attack_mahalanobis_dp / attack_mahalanobis_no_aux_dp in place of the
standard variants.  They accept two additional keyword arguments:

    dp_epsilon  : float     — ε privacy budget
    dp_delta    : float     — δ failure probability
    dp_n_cells  : int       — total cells for this cell type in D_train
    dp_k_max    : int       — max cells any donor contributes (this cell type)
    dp_clip     : float     — quantile-normal clip bound (default 3.0)
    dp_rng      : np.random.Generator | None  — for reproducibility

These are passed as a single `dp_params` dict for cleanliness.
"""

import sys
import os
import numpy as np

_SRC_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

from sdg.scdesign2.copula import parse_copula, build_shared_covariance_matrix, get_shared_genes
from attacks.scmamamia.scoring import compute_cell_scores
from sdg.dp.dp_copula import apply_gaussian_dp


# ---------------------------------------------------------------------------
# Helper: convert rpy2 copula to parsed dict then apply DP noise
# ---------------------------------------------------------------------------

def _parse_and_noise(copula_r, dp_params: dict) -> dict:
    """
    Parse an rpy2 copula object, apply DP noise to cov_matrix, return dict.

    dp_params keys: epsilon, delta, n_cells, k_max, clip_value, rng
    """
    parsed = parse_copula(copula_r)
    noised = apply_gaussian_dp(
        copula_dict=parsed,
        epsilon=dp_params["epsilon"],
        delta=dp_params["delta"],
        n_cells=dp_params["n_cells"],
        k_max=dp_params["k_max"],
        clip_value=dp_params.get("clip_value", 3.0),
        rng=dp_params.get("rng"),
    )
    return noised


# ---------------------------------------------------------------------------
# Attack: Mahalanobis with DP noise on the synthetic copula
# ---------------------------------------------------------------------------

def attack_mahalanobis_dp(cfg, targets, cell_type, copula_synth_r,
                           copula_aux_r=None, dp_params: dict | None = None):
    """
    DP-aware version of attack_mahalanobis.

    The synthetic copula's covariance is noised before the attack proceeds.
    The auxiliary copula is left unchanged (it is not released with DP noise).

    Parameters
    ----------
    cfg, targets, cell_type, copula_synth_r, copula_aux_r
        — same as attack_mahalanobis
    dp_params : dict with keys:
        epsilon    : float
        delta      : float
        n_cells    : int   — cells for this cell type in training set
        k_max      : int   — max cells per donor for this cell type
        clip_value : float (default 3.0)
        rng        : np.random.Generator | None
    """
    if dp_params is None:
        raise ValueError("dp_params must be provided for attack_mahalanobis_dp")

    cs = _parse_and_noise(copula_synth_r, dp_params)
    ca = parse_copula(copula_aux_r)

    covariate_genes, _ = get_shared_genes(
        cs["primary_genes"], cs["secondary_genes"],
        ca["primary_genes"], ca["secondary_genes"],
    )

    # For the noised copula, cov_matrix is already a numpy array; use it directly.
    n_shared = len(covariate_genes)
    gene_indices_s = [cs["primary_genes"].index(g) for g in covariate_genes]
    noised_cov_np   = cs["cov_matrix"]
    shared_cov_s    = noised_cov_np[np.ix_(gene_indices_s, gene_indices_s)]
    marginals_s_np  = cs["primary_marginals"]
    shared_margs_s  = marginals_s_np[gene_indices_s]

    shared_cov_a, shared_margs_a = build_shared_covariance_matrix(
        covariate_genes, ca["primary_genes"], ca["cov_matrix"], ca["primary_marginals"]
    )

    inv_s = cfg.lin_alg_inverse_fn(shared_cov_s)
    inv_a = cfg.lin_alg_inverse_fn(shared_cov_a)

    X  = targets[covariate_genes].values   # (N, G)
    G  = n_shared
    pi_s, theta_s, mu_s = shared_margs_s[:, 0], shared_margs_s[:, 1], shared_margs_s[:, 2]
    pi_a, theta_a, mu_a = shared_margs_a[:, 0], shared_margs_a[:, 1], shared_margs_a[:, 2]

    mapped_s = np.empty_like(X, dtype=float)
    mapped_a = np.empty_like(X, dtype=float)
    mean_s   = np.empty(G, dtype=float)
    mean_a   = np.empty(G, dtype=float)
    remap = cfg.uniform_remapping_fn
    for j in range(G):
        mapped_s[:, j] = remap(X[:, j], pi_s[j], theta_s[j], mu_s[j])
        mapped_a[:, j] = remap(X[:, j], pi_a[j], theta_a[j], mu_a[j])
        mean_s[j]      = remap(mu_s[j],  pi_s[j], theta_s[j], mu_s[j])
        mean_a[j]      = remap(mu_a[j],  pi_a[j], theta_a[j], mu_a[j])

    delta_s = mapped_s - mean_s
    delta_a = mapped_a - mean_a

    d_s = np.sqrt(np.einsum("ij,jk,ik->i", delta_s, inv_s, delta_s))
    d_a = np.sqrt(np.einsum("ij,jk,ik->i", delta_a, inv_a, delta_a))

    scores = d_a / (d_s + d_a)
    nan_mask = np.isnan(scores)
    if nan_mask.any():
        scores = scores.copy()
        scores[nan_mask] = 0.5
        print(f"  [WARN-DP] {nan_mask.sum()} NaN scores for {cell_type} — set to 0.5")

    return compute_cell_scores(cfg, cell_type, scores, targets,
                               d_s.tolist(), d_a.tolist())


def attack_mahalanobis_no_aux_dp(cfg, targets, cell_type, copula_synth_r,
                                  copula_aux_r=None, dp_params: dict | None = None):
    """
    DP-aware version of attack_mahalanobis_no_aux.

    Parameters
    ----------
    dp_params : dict — same keys as attack_mahalanobis_dp
    """
    if dp_params is None:
        raise ValueError("dp_params must be provided for attack_mahalanobis_no_aux_dp")

    cs = _parse_and_noise(copula_synth_r, dp_params)

    n_genes = len(cs["primary_genes"])
    cov_np  = cs["cov_matrix"]   # already numpy, already noised
    inv_s   = cfg.lin_alg_inverse_fn(cov_np)

    X  = targets[cs["primary_genes"]].values
    G  = n_genes
    marginals_np = cs["primary_marginals"]
    pi_s, theta_s, mu_s = marginals_np[:, 0], marginals_np[:, 1], marginals_np[:, 2]

    mapped_s = np.empty_like(X, dtype=float)
    mean_s   = np.empty(G, dtype=float)
    remap = cfg.uniform_remapping_fn
    for j in range(G):
        mapped_s[:, j] = remap(X[:, j], pi_s[j], theta_s[j], mu_s[j])
        mean_s[j]      = remap(mu_s[j],  pi_s[j], theta_s[j], mu_s[j])

    delta_s = mapped_s - mean_s
    d_s = np.sqrt(np.einsum("ij,jk,ik->i", delta_s, inv_s, delta_s))

    scores = 1.0 / (d_s + cfg.mamamia_params.epsilon)
    nan_mask = np.isnan(scores)
    if nan_mask.any():
        scores = scores.copy()
        scores[nan_mask] = 0.5
        print(f"  [WARN-DP] {nan_mask.sum()} NaN scores for {cell_type} — set to 0.5")

    return compute_cell_scores(cfg, cell_type, scores, targets, d_s.tolist(), None)
