"""
scMAMA-MIA: Membership Inference Attack against synthetic scRNA-seq data.

Black-box (BB) attack with Class B focal points.

Usage
-----
  # With auxiliary data (BB+aux — recommended):
  python run_attack.py \\
    --synth-h5ad    /path/to/synthetic.h5ad \\
    --target-h5ad   /path/to/target.h5ad \\
    --train-donors  /path/to/train_donors.npy \\
    --aux-h5ad      /path/to/auxiliary.h5ad \\
    --hvg-csv       /path/to/hvg.csv \\
    --out-csv       results/predictions.csv

  # Without auxiliary data (BB-aux — weaker):
  python run_attack.py \\
    --synth-h5ad    /path/to/synthetic.h5ad \\
    --target-h5ad   /path/to/target.h5ad \\
    --train-donors  /path/to/train_donors.npy \\
    --hvg-csv       /path/to/hvg.csv \\
    --out-csv       results/predictions.csv

Inputs
------
  synth-h5ad    : Synthetic data generated by the target SDG.  Used to fit
                  the shadow copulas (BB: we run scDesign2 on this data).
  target-h5ad   : AnnData of cells to score.  Must have obs columns:
                    'individual' (or the value of --individual-col): donor ID
                    'cell_type':                                      cell type
  train-donors  : .npy file with the list of training donor IDs.
                  Donors in this list are labeled as members (1);
                  all others as non-members (0).
                  Alternative: if the target h5ad already has a 'member' obs
                  column (0/1), omit --train-donors.
  aux-h5ad      : (Optional) Auxiliary reference dataset.  If omitted the
                  attack runs in BB-aux mode (lower accuracy).
  hvg-csv       : (Optional) CSV with a 'highly_variable' boolean column
                  (one row per gene).  Computed automatically if not provided.

Outputs
-------
  out-csv : CSV with columns: donor_id, true_membership, predicted_score
            Rows are donors in the target dataset.
            Optionally prints ROC AUC to stdout if true labels are available.
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd
import anndata as ad

# Ensure the scMAMA-MIA directory is importable
_DIR = os.path.dirname(os.path.abspath(__file__))
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)

from copula import load_copula
from cdf_utils import zinb_uniform_transform
from attack import attack_mahalanobis_classb_bb, attack_mahalanobis_classb_bb_noaux
from scoring import merge_cell_type_results, aggregate_to_donor
from shadow_model import fit_shadow_copulas

from numpy.linalg import pinv as _pinv


# ---------------------------------------------------------------------------
# Config defaults
# ---------------------------------------------------------------------------

ATTACK_CFG_DEFAULTS = {
    "uniform_remapping_fn": zinb_uniform_transform,
    "lin_alg_inverse_fn":   _pinv,
    "epsilon":              1e-10,    # numerical stability floor
    "class_b_gamma":        "auto",   # weight for secondary-gene LLR
    "class_b_gamma_noaux":  0.0,      # disabled for BB-aux
    "class_b_gene_set":     "secondary",
}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="scMAMA-MIA: BB(+/- aux) membership inference attack"
    )
    ap.add_argument("--synth-h5ad",     required=True,
                    help="Synthetic data used to fit shadow copulas")
    ap.add_argument("--target-h5ad",    required=True,
                    help="Target AnnData with cells to score")
    ap.add_argument("--train-donors",   default=None,
                    help=".npy file of training donor IDs (members); "
                         "OR omit if target h5ad has a 'member' obs column")
    ap.add_argument("--aux-h5ad",       default=None,
                    help="Auxiliary reference data (optional; omit for BB-aux)")
    ap.add_argument("--hvg-csv",        default=None,
                    help="HVG mask CSV; auto-computed if absent")
    ap.add_argument("--out-csv",        required=True,
                    help="Output CSV path for per-donor predictions")
    ap.add_argument("--individual-col", default="individual",
                    help="obs column for donor IDs (default: individual)")
    ap.add_argument("--cell-type-col",  default="cell_type",
                    help="obs column for cell types (default: cell_type)")
    ap.add_argument("--n-workers",      type=int, default=4,
                    help="Parallel processes for shadow model fitting (default: 4)")
    ap.add_argument("--shadow-dir",     default=None,
                    help="Directory for shadow copula .rds files (tmp dir if absent)")
    args = ap.parse_args()

    use_aux = args.aux_h5ad is not None

    # ------------------------------------------------------------------
    # 1. Fit shadow copulas on synthetic data
    # ------------------------------------------------------------------
    print(f"\n=== Fitting shadow copulas on synthetic data ===", flush=True)
    shadow_dir = args.shadow_dir or os.path.join(
        os.path.dirname(args.out_csv), "shadow_copulas_synth"
    )
    synth_copulas = fit_shadow_copulas(
        h5ad_path     = args.synth_h5ad,
        output_dir    = shadow_dir,
        hvg_csv       = args.hvg_csv,
        cell_type_col = args.cell_type_col,
        n_workers     = args.n_workers,
    )
    if not synth_copulas:
        print("ERROR: No synth copulas were fitted successfully.", flush=True)
        sys.exit(1)

    # ------------------------------------------------------------------
    # 2. Fit shadow copulas on auxiliary data (if provided)
    # ------------------------------------------------------------------
    aux_copulas = {}
    if use_aux:
        print(f"\n=== Fitting shadow copulas on auxiliary data ===", flush=True)
        aux_shadow_dir = args.shadow_dir.rstrip("/") + "_aux" if args.shadow_dir \
                         else os.path.join(os.path.dirname(args.out_csv),
                                           "shadow_copulas_aux")
        aux_copulas = fit_shadow_copulas(
            h5ad_path     = args.aux_h5ad,
            output_dir    = aux_shadow_dir,
            hvg_csv       = args.hvg_csv,
            cell_type_col = args.cell_type_col,
            n_workers     = args.n_workers,
        )

    # ------------------------------------------------------------------
    # 3. Load target data and label members
    # ------------------------------------------------------------------
    print(f"\n=== Loading target data ===", flush=True)
    target = ad.read_h5ad(args.target_h5ad)

    if "member" in target.obs.columns:
        membership = target.obs["member"].astype(int).values
    elif args.train_donors:
        train_ids = np.load(args.train_donors, allow_pickle=True)
        membership = target.obs[args.individual_col].isin(set(train_ids)).astype(int).values
    else:
        print("WARNING: --train-donors not provided and 'member' column absent. "
              "All donors will be treated as non-members (membership = 0). "
              "AUC will not be computed.", flush=True)
        membership = np.zeros(len(target), dtype=int)

    target.obs["member"]     = membership
    target.obs["individual"] = target.obs[args.individual_col]
    print(f"  {target.n_obs:,} cells, {target.obs['individual'].nunique()} donors",
          flush=True)
    print(f"  {membership.sum():,} member cells, {(1-membership).sum():,} non-member cells",
          flush=True)

    # HVG list for gene subsetting
    hvg_genes = _get_hvg_genes(synth_copulas, args.cell_type_col)

    # ------------------------------------------------------------------
    # 4. Attack each cell type
    # ------------------------------------------------------------------
    print(f"\n=== Running scMAMA-MIA attack ({'BB+aux' if use_aux else 'BB-aux'}) ===",
          flush=True)
    cfg = dict(ATTACK_CFG_DEFAULTS)
    results = []

    cell_types = sorted(set(synth_copulas.keys()) & set(target.obs[args.cell_type_col].unique()))

    for ct in cell_types:
        synth_rds = synth_copulas.get(ct)
        if synth_rds is None or not os.path.exists(synth_rds):
            print(f"  [SKIP] {ct}: no synth copula", flush=True)
            results.append((ct, None, 0.0))
            continue

        if use_aux:
            aux_rds = aux_copulas.get(ct)
            if aux_rds is None or not os.path.exists(aux_rds):
                print(f"  [SKIP] {ct}: no aux copula", flush=True)
                results.append((ct, None, 0.0))
                continue

        # Load copulas via rpy2
        copula_synth = load_copula(synth_rds, ct)

        # Build target DataFrame for this cell type
        mask_ct = target.obs[args.cell_type_col] == ct
        sub     = target[mask_ct].to_memory() if hasattr(target, "file") else target[mask_ct]
        sub_df  = _build_target_df(sub, hvg_genes, args.cell_type_col)

        if sub_df is None or len(sub_df) == 0:
            print(f"  [SKIP] {ct}: no target cells", flush=True)
            results.append((ct, None, 0.0))
            continue

        import time
        t0 = time.process_time()
        try:
            if use_aux:
                copula_aux = load_copula(aux_rds, ct)
                result_df = attack_mahalanobis_classb_bb(
                    cfg, sub_df, ct, copula_synth, copula_aux
                )
            else:
                result_df = attack_mahalanobis_classb_bb_noaux(
                    cfg, sub_df, ct, copula_synth
                )
        except Exception as e:
            print(f"  [ERROR] {ct}: {e}", flush=True)
            results.append((ct, None, 0.0))
            continue

        rt = time.process_time() - t0
        results.append((ct, result_df, rt))
        print(f"  Done: {ct}  ({len(sub_df):,} cells, {rt:.1f}s)", flush=True)

    # ------------------------------------------------------------------
    # 5. Aggregate to donor level
    # ------------------------------------------------------------------
    print(f"\n=== Aggregating to donor level ===", flush=True)
    merged, total_rt = merge_cell_type_results(results, use_aux=use_aux)

    if len(merged) == 0:
        print("ERROR: No results to aggregate.", flush=True)
        sys.exit(1)

    true_labels, predictions, donor_ids = aggregate_to_donor(merged, use_aux=use_aux)

    out_df = pd.DataFrame({
        "donor_id":          donor_ids,
        "true_membership":   true_labels,
        "predicted_score":   predictions,
    })
    os.makedirs(os.path.dirname(os.path.abspath(args.out_csv)), exist_ok=True)
    out_df.to_csv(args.out_csv, index=False)
    print(f"\nPredictions saved → {args.out_csv}  ({len(out_df)} donors)", flush=True)

    # ------------------------------------------------------------------
    # 6. Compute AUC if labels are available
    # ------------------------------------------------------------------
    if len(set(true_labels)) == 2:
        from sklearn.metrics import roc_auc_score
        auc = roc_auc_score(true_labels, predictions)
        print(f"\nROC AUC = {auc:.4f}  (donor-level, {'BB+aux' if use_aux else 'BB-aux'})",
              flush=True)
    else:
        print("\n(Cannot compute AUC: only one class present in labels)", flush=True)

    print(f"Total attack runtime: {total_rt:.1f}s", flush=True)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_target_df(sub_adata, hvg_genes, cell_type_col):
    """Build per-cell DataFrame with HVG expression + individual + member columns."""
    available = [g for g in hvg_genes if g in sub_adata.var_names]
    if not available:
        return None
    df = sub_adata[:, available].to_df()
    df["individual"] = sub_adata.obs["individual"].values
    df["member"]     = sub_adata.obs["member"].values
    return df


def _get_hvg_genes(copula_paths, cell_type_col):
    """
    Extract the HVG gene list from any fitted shadow copula .rds file.
    Falls back to a union of primary + secondary genes across cell types.
    """
    if not copula_paths:
        return []
    ct  = next(iter(copula_paths))
    rds = copula_paths[ct]
    try:
        cpd = load_copula(rds, ct)
        return cpd["primary_genes"] + cpd["secondary_genes"]
    except Exception:
        return []


if __name__ == "__main__":
    main()
